### ISSUE TITLE
problem statement review

### ISSUE THREAD

**Issue by gordonwky** [gordonwky/GMM_EM#1]

**Comment by smiths** [comment]
@gordonwky, please provide a link to your problem statement in the issue to facilitate the review.  :smile:

**Comment by gordonwky** [comment]
https://github.com/gordonwky/GMM_EM/tree/main/docs/ProblemStatementAndGoals

**Comment by gordonwky** [comment]
The repo contains the pdf and tex file
https://github.com/gordonwky/GMM_EM/tree/main/docs/ProblemStatementAndGoals

Spencer Smith ***@***.***> 於 2024年1月19日週五 下午6:34寫道：

**Comment by gordonwky** [comment]
https://github.com/gordonwky/GMM_EM/blob/main/docs/ProblemStatementAndGoals/cas741_problem_statement.pdf 

This is the pdf

**Comment by smiths** [comment]
Feedback:

- you can use markdown to make nice [links](https://github.com/gordonwky/GMM_EM/blob/main/docs/ProblemStatementAndGoals/cas741_problem_statement.pdf), instead of writing out the entire url
- you need to think whether your project will be a library, or a program.  The only difference is that in the program version you have a user-facing interface
- it would be nice to see some equations in the problem statement :smile:
- not using external libraries is probably not feasible, or even desirable.  Your obligation for testing goes up much higher if you are writing all of your own code

The project sounds interesting.  I'm looking forward to it.  We'll need to keep an eye on the scope to make sure it isn't too much work.

Your project is approved.
